apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1-container
        image: amalghazala11/lab22-image:v1.0
        ports:
        - containerPort: 80  # Port the container listens on

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80  # Port to expose service
      targetPort: 80
  type: LoadBalancer  # Use ClusterIP, NodePort, or LoadBalancer based on your setup
